server:
  port: 80
# 服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  server:
    enableSelfPreservation: false
  client:
    #是否向服务注册中心注册自己
    registerWithEureka: false
    #是否检索服务
    fetchRegistry: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring.profiles: es1
server:
  port: 81
eureka:
  instance:
    hostname: eurekaServer1
  client:
    serviceUrl.defaultZone: http://localhost:82/eureka/

---
spring.profiles: es2
server:
  port: 82
eureka:
  instance:
    hostname: eurekaServer1
  client:

    serviceUrl.defaultZone: http://localhost:81/eureka/