server:
  port: 8010
spring:
  # 配置应用实例在eureka中的名称
  application:
    name: uam
# 配置eureka服务端地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:81/eureka/,http://localhost:82/eureka/

---
spring.profiles: s1
server.port: 8011

---
spring.profiles: s2
server.port: 8012