server:
  port: 8010
spring:
  # 配置应用实例在eureka中的名称
  application:
    name: uam
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
    - classpath:/templates
# 配置eureka服务端地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:81/eureka/,http://localhost:82/eureka/

---
spring.profiles: s1
server.port: 8011

---
spring.profiles: s2
server.port: 8012